server:
  display-name: MGS System
spring:
  application:
    name: MGS
spring.datasource:
  url: jdbc:hsqldb:file:db/mgs;shutdown=true
  username: SA
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true
spring.mvc.throw-exception-if-no-handler-found: true
spring.resources.add-mappings: false
mgs:
  policy:
    executor:
      interval-hours: 1
  door:
    proxy-server:
      aio:
        handler-thread-cnt: 10
      io-mode: AIO
      port: 8443
      accept-thread-cnt: 1
      read-timeout-secs: 10
      write-timeout-secs: 10
      listener-thread-cnt: 10
      keep-alive-secs: 300
      keystore:
        password: changeme
    
security.basic.enabled: false

---
spring:
  profiles: alpha
server.port: 443
server.ssl.key-store: classpath:www.pfx
server.ssl.key-store-password: changeme
server.ssl.key-password: changeme

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/mgs?useSSL=false
    username: root
    password: symantec12
    driver-class-name: com.mysql.jdbc.Driver
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  
---
spring:
  profiles: ut
  datasource:
    url: jdbc:hsqldb:mem:test;shutdown=true
    username: SA